### ISSUE TITLE
Implement Insertion sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#11]
- Please help me implement `Insertion sort` algorithm in `/sorting/insertion-sort.js`
- You must write test cases for it, in `/tests/sorting/insertion-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by ialixandroae** [comment]
I will do it.
