### ISSUE TITLE
Implement Comb sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#14]
- Please help me implement `Comb sort` algorithm in `/sorting/comb-sort.js`
- You must write test cases for it, in `/tests/sorting/comb-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by vsnehil92** [comment]
I would like to take up this issue.
