### ISSUE TITLE
Implement Gnome sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#16]
- Please help me implement `Gnome sort` algorithm in `/sorting/gnome-sort.js`
- You must write test cases for it, in `/tests/sorting/gnome-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by CliffReimers** [comment]
I will take this on

**Comment by euclid1990** [comment]
@CliffReimers yes, you are welcome

**Comment by euclid1990** [comment]
All issues are never closed.
Even if a pull request related it is mered, you can still send the other pull request associated with this issue. Examples include: performance improvement, refactoring code, ... 👍 If you edit source code file, please add your name in author section 
![image](https://user-images.githubusercontent.com/5584709/46341660-fab41280-c662-11e8-9498-b801373c62a5.png)
