### ISSUE TITLE
Implement Quick sort algorithm 

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#2]
- Please help me implement `Quick sort` algorithm in `/sorting/quick-sort.js`
- You must write test cases for it, in `/tests/sorting/quick-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by B1tF8er** [comment]
Hello, could I help with this?

**Comment by euclid1990** [comment]
@B1tF8er Yes !

**Comment by B1tF8er** [comment]
Could you please assign me this issue? thanks!

**Comment by euclid1990** [comment]
@B1tF8er I have been try to assigned to you, but not found any result !
![image](https://user-images.githubusercontent.com/5584709/46331513-84071d00-c642-11e8-914f-2a2e9699a179.png)

**Comment by B1tF8er** [comment]
no worries I will create the PR soon

**Comment by B1tF8er** [comment]
I have an  issue with my authentication, I wont be able to do this PR, sorry :(

**Comment by B1tF8er** [comment]
Solved my auth Issue and created a PR, if you could review that would be awesome
