### ISSUE TITLE
Implement Merge sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#3]
- Please help me implement `Merge sort` algorithm in `/sorting/merge-sort.js`
- You must write test cases for it, in `/tests/sorting/merge-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by bagmarnikhil** [comment]
Hello, I could help with this issue ?

**Comment by pandaa880** [comment]
Is this issue closed ?

**Comment by bagmarnikhil** [comment]
I think this issue is closed, will find something else.

**Comment by euclid1990** [comment]
@bagmarnikhil @pandaa880 All issues are never closed. 
Even if a pull request related it is mered, you can still send the other pull request associated with this issue. Examples include: performance improvement, refactoring code, ... 👍 
If you edit source code file, please add your name in author section
![image](https://user-images.githubusercontent.com/5584709/46341660-fab41280-c662-11e8-9498-b801373c62a5.png)
