### ISSUE TITLE
Implement Heap sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#4]
- Please help me implement `Heap sort` algorithm in `/sorting/heap-sort.js`
- You must write test cases for it, in `/tests/sorting/heap-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by methusael13** [comment]
Hi, I'd like to implement this. Could you assign it to me?
