### ISSUE TITLE
Implement Shell sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#7]
- Please help me implement `Shell sort` algorithm in `/sorting/shell-sort.js`
- You must write test cases for it, in `/tests/sorting/shell-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by B1tF8er** [comment]
I would like to work on this
