### ISSUE TITLE
Implement Bucket sort algorithm

### ISSUE THREAD

**Issue by euclid1990** [euclid1990/js-challenges#9]
- Please help me implement `Counting sort` algorithm in `/sorting/bucket-sort.js`
- You must write test cases for it, in `/tests/sorting/bucket-sort.spec.js` 
- Please read __Dev guidelines__ in [README.md](../blob/master/README.md#contribute) before creating any Pull request !
- Refer this file for comment convention. [bubble-sort.js](https://github.com/euclid1990/js-challenges/blob/master/sorting/bubble-sort.js). Example: Change author name to your name, ...

Thank you 🤣

**Comment by eyalrosenbaum** [comment]
I would like to do this as my first issue
